metadata:
    version: 0.1.4

settings:
    power: 250000000
    comment: The Hallam Nuclear Power Facility Startup core from 1964
    loadingFile: hallam_bp.yaml
    verbosity: debug
    xsKernel: DRAGON
    genXS: Neutron
    numcycles: 1
    dragonExePath: /pool/Software/Nuclear/DRAGON/Version5_beta_ev1462/Dragon/bin/Linux_x86_64/Dragon
    dragonDataPath: /pool/Software/Nuclear/DRAGON/nucleardata/draglibendfb8r0SHEM361

